### ISSUE TITLE
Attempting to recreate analysis on Virgin River to replicate on San Pedro afterwards

### ISSUE THREAD

**Issue by zancona** [jtgilbert/VBET-2#18]
Hello, I am trying to create some valley bottom polygon estimates for the Virgin River so I can transfer the methods to another river that has not been completed yet by your group. But the Virgin was a good place to start, so that I can compare outputs I get to the ones you all have created. 

I have pretty minimal experience using python, but have been using the new VBET tool and just have a few issues that I am running into that I'm sure are simple fixes that I am just doing something incorrect with the way I am setting it up.

I created my stream network,  (started with NHD, but there were too many small artifacts along the river that made the segmenting process very difficult). I then created a river network from the DEM using a flow accumulation raster and believe I have a good river network to feed into the tool. But I am getting some strange errors with it accessing certain .py scripts after it starts generating my drainage network, or something else may be going on.

Any help on my issues would be amazing! Thank you! 
-Zach

For some reason I can't attach a screenshot or file to this message, so I will describe the error below I am getting in the command prompt.

Adding drainage area to network
Cleaning up drainage network for VBET input
starting with 184 network segments
cleaned 182 network segments
Generating valley bottom for each network segment
0%
Traceback (most recent call last):
File "C:\Users\jordang\Desktop\VBET-2-master\VBET.py", line 59, in vbet inst.run()
File "run_VBET.py", line 31, in run vb.valley_bottom()
File classVBET.py", line 486, in valley_bottom slope_sub = self.reclassify(slope, ndval, self.sm_slope)
File classVBET.py", line 305, in reclassify array[j,i] = ndval
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jtgilbert** [comment]
Thanks for emailing me about this, I'll be looking into it shortly.
