### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by jaywt** [jtgilbert/VBET-2#5]
Hi,

Tried to use VBET-2 to delineate valley bottom for Shaver's Creek around State College in PA. Use 3m DEM, as well as DA layer derived from the same 3m DEM. In addition, stream flow line from NHG was used. 

As run the codes, got the error saying "ZeroDivisionError as below:

`(vbet_niu) XXXXXXXX:VBET2 XXXXXX$ python run_VBET_SC.py 
segment  1  of  173

Traceback (most recent call last):
  File "run_VBET_SC.py", line 26, in <module>
    vb.valley_bottom()
  File "/Users/xxxxxxx/Desktop/VBET2/VBET.py", line 374, in valley_bottom
    detr = self.detrend(dem, geom)  # might want to change this offset
  File "/Users/xxxxxxx/Desktop/VBET2/VBET.py", line 148, in detrend
    xs[i] = int(float(_xs[i] - x_min) / float(res_x))  # column in array space
ZeroDivisionError: float division by zero`

**Comment by wwicherski** [comment]
I am also experiencing the exact same issue.  

I am trying to run this code for a DEM near Pagosa Springs.

**Comment by jtgilbert** [comment]
This was an issue with an update to rasterio. The newest release will use the new version of rasterio with this issue fixed
